name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install mkdocs
      run: pip install --upgrade pip
           pip install mkdocs
           pip install mkdocs-material
           pip install mkdocs-git-authors-plugin
           pip install mkdocs-git-revision-date-localized-plugin
           pip install mkdocs-git-committers-plugin
           pip install mkdocs-glightbox
           pip install mkdocs-img2fig-plugin
           pip install mkdocs-mermaid2-plugin
           # pip install mkdocs-simple-plugin==2.2.0
    
    - name: Build and push docs
      uses: athackst/mkdocs-simple-plugin@v2.2.0
      with:
        #   # (optional) Specify branch 
        #   publish_branch: main # gh-pages 
          # (optional) The URL of the repository the docs should point to
          repo_url: https://github.com/dcaddick/gsd_test2
          # (optional) The URL of the site
          site_url: https://dcaddick.github.io
          # (optional) The edit URI
          edit_uri: edit/main/
        #   # (optional) Specify a google analytics key 
        #   # google_analytics: G-QS5J5W9G3Q
        #   # (optional) Specify a different theme [mkdocs|readthedocs|material]
          theme: material
        #   # (optional) Load a configuration file from a string
          config: "mkdocs.yml"
    
#    - name: Build
#      run: mkdocs build
#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./public
